---
- hosts: webservers
  gather_facts: False
  become: yes
  become_method: su
  vars_files:
    - "../vars/main.yml"
  tasks:
    - name: "Add {{ deploy_user }} user"
      user:
        name: "{{ deploy_user }}"
        createhome: "yes"
        shell: "/bin/bash"
        state: "present"

    - name: "Create {{ deploy_dirs }} dirs"
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: 0700
      with_items: "{{ deploy_dirs }}"

    - name: "Ensure sudo is installed"
      raw: apt install -y sudo

    - name: "Create sudoer config for {{ deploy_user }}"
      template:
        src: "../templates/sudoers.j2"
        dest: "/etc/sudoers.d/{{ deploy_user }}-{{ app_name }}"
        owner: root
        group: root
        mode: 0600

    - name: "Copy systemd config file"
      template:
        src: "../templates/systemd.j2"
        dest: "/etc/systemd/system/{{ app_name }}.service"
        owner: root
        group: root
        mode: 0644

    - name: Enable Systemd service for application
      systemd:
        name: "{{ app_name }}"
        enabled: yes

    - name: "Copy nginx site configuration"
      template:
        src: "../templates/nginx-site.j2"
        dest: "/etc/nginx/conf.d/{{ app_name }}.conf"
        owner: root
        group: root
        mode: 0600
