---
- hosts: webservers
  gather_facts: False
  become: yes
  become_method: su
  vars_files:
    - "../vars/main.yml"
  tasks:
    - name: "Add {{ deploy_group }} group"
      group: name={{ deploy_group }} state=present

    - name: "Add {{ deploy_user }} user"
      user: name={{ deploy_user }} groups={{ deploy_group }} append=yes state=present

    - name: "Ensure ownership of {{ deploy_user }} home directory"
      raw: chown {{ deploy_user }}:{{ deploy_user }} -R /home/{{ deploy_user }}

    - name: "Remove password for {{ deploy_user }} user"
      raw: passwd -d {{ deploy_user }}

    - name: "Create {{ deploy_dirs }} dirs"
      file: path={{ item }} state=directory owner={{ deploy_user }} group={{ deploy_group }} mode=0700
      with_items: "{{ deploy_dirs }}"
